### ISSUE TITLE
Understanding the block diagonal gene expression matrix

### ISSUE THREAD

**Issue by jasminelmah** [atarashansky/SAMap#56]
Thanks for developing SAMap! It is such a valuable tool for cross-species comparisons and I'm really excited to use it.

I was reading your SAMap vignette, which has been very helpful! Would you be able to give me a little more insight into how to interpret the block diagonal matrix of each species' gene expressions (stored in samap.adata)? Are these corrected gene expression values that would allow me to directly compare the expression level of one ortholog in a particular species to that of another ortholog in another species (in a way "batch-correcting" at the species level)? If so, is there a way to obtain this for all genes in the original scRNAseq expression matrix? Thanks for your help!

**Comment by atarashansky** [comment]
Hello! Thanks for your patience.

In `samap==0.3.2`, I added two new functions to determine the expression correlations between two genes. Check out the `Querying gene mappings` section in `SAMap_vignette.ipynb`.

Two new functions: 
`sm.query_gene_pairs("gene id")`  <-- returns all genes connected to `gene id`
`sm.query_gene_pair("gene id 1", "gene id 2")`  <-- returns edge weight between `gene id 1` and `gene id 2`.

Preferrably, the gene IDs are prepended with their species IDs. So, for example, `hu_SOX2` instead of `SOX2`.

Let me know if this is helpful for you or if I didn't properly address your question.

**Comment by jasminelmah** [comment]
Hi!

Wow, thank you very  much! These new functions will be very helpful and I
look forward to trying them out. I really appreciate the time and effort
you put into this.
