### ISSUE TITLE
export plots

### ISSUE THREAD

**Issue by Bassi-git** [atarashansky/SAMap#60]
Hi,

Thank you for this amazing tool, it is really a pleasure to use!
I have one problem though with exporting the sankey plot. The interactive save option is nice, but so far I failed to find a way to export the plot as a high quality image or vector graphic with this option.
In a previous version (unfortunately don't remember which one) this worked great instead:

p = sankey_plot(MappingTable, align_thr=0.1)
import holoviews as hv
hv.extension('matplotlib')
hv.save(obj=p, filename='...', fmt='svg')

Now I am running version 0.3.1 and when I try to export the plot with that same code, all the ribbons are just one equally thick line and the cell type bars all have the same size. So it seems like the alignment score is not reflected.

I apologize if there is an obvious solution to this, that I missed, but I would be really glad, if you could point me towards it!
Thanks a lot!

**Comment by atarashansky** [comment]
Hmm, it's surprising your snippet worked in a previous version since the sankey plot SAMap produces uses the bokeh extension. Some of the parameters I'm using to format the sankey plot style only works for bokeh. And unfortunately, Bokeh doesn't support svg output.

Do you remember which SAMap version your snippet worked well?

**Comment by Bassi-git** [comment]
Hi, 
Thanks for the quick reply!
It was probably version 0.1.3 or 0.1.6
